/* Declarations */
/// <reference path="../../lib/user.d.ts"/>
/// <reference path="../../lib/app.d.ts"/>
/// <reference path="../../lib/jquery.d.ts"/>
/* Page files */
/// <reference path="./RoomPage.ts"/>
/* Models */
/// <reference path="./room.ts"/>
/// <reference path="./socket.ts"/>
/* Tabs */
/// <reference path="./tab.ts"/>
/* Tools */
/// <reference path="./tabs/tool.ts"/>
/// <reference path="./tabs/tools/add.ts"/>
/// <reference path="./tabs/tools/zoomin.ts"/>
/// <reference path="./tabs/tools/zoomout.ts"/>
/// <reference path="./tabs/tools/save.ts"/>
/// <reference path="./tabs/tools/load.ts"/>
/// <reference path="./tabs/tools/clear.ts"/>
/* Views */
/// <reference path="./RoomView.ts"/>
/// <reference path="./views/RoomMobileView.ts"/>
/* Whiteboard */
/// <reference path="./whiteboard.ts"/>
/// <reference path="./whiteboard/whiteboardmodule.ts"/>
/// <reference path="./whiteboard/whiteboardmoduleview.ts"/>
/// <reference path="./whiteboard/modules/textmodule.ts"/>
/// <reference path="./whiteboard/modules/drawmodule.ts"/>